version: '3'  

services:  
  pulsar:  
    image: apachepulsar/pulsar:latest  
    command: ["bin/pulsar", "standalone"]  
    ports:  
      - "6650:6650"  
      - "8089:8080"
    volumes:  
      - pulsardata:/pulsar/data  

volumes:  
  pulsardata: