spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - PrefixPath=/api
        - id: order-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - PrefixPath=/api

      discovery:
        locator:
          enabled: true


  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
